### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Guy-Gustave**
this is the pull request i made after created an association, in the projects private-events

### CODE REVIEW

**Review by peterrobert — CHANGES_REQUESTED** [review]
### CHANGES REQUIRED :recycle: :stop_button: 
### HELLO @Guy-Gustave VERY NICE WORK SO FAR YOU HAVE DONE A NICE JOB :+1:  HOWEVER JUST A FEW CHANGES TO BE MADE.

- [ ] There is an error in the create function. We can't seem to persist the data to the database kindly fix this
errors

- [ ] kindly add login in your menu bar. we need to be able to create a new user just like stated :arrow_down: 

log in

- [ ] Very great work I can see you don't have any logic in your views :clap:  Kindly fix the above and the next  TSE will be able to give you a full review

### If you have any questions reach me on slack @peterrobert

### HAPPY CODING :computer:

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Guy Nigaba** 
I see you have implemented some of the improvements required by the previous TSE :muscle:  :muscle: 
But some others weren't implemented, so you still need to work in some issues:

- [ ] An error occurs when I try to create an event
- [ ] An error occurs when I try to login with a created user
- [ ] you have commented code in new.html.erb
- [ ] you have a close tag '%>' in new.html.erb which doesn't match any open tag.
- [ ] change the name of the branch for a more descriptive one (you might use feature or similar).


Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

**Comment by Guy-Gustave** [comment]
I fixed the errors I did. and change the branch name. now all works perfectly.thanx

**Comment by kubilaycaglayan** [comment]
Hello Team :wave: 
Status: Invalid Code Review Request :no_entry_sign: 

:bulb: You should either **open a new pull request for the new branch** you have created OR **merge that new branch into this branch**. Since there are no commits or any changes to review here in this branch, this code review request has been marked as invalid. :blush: 

It is all fine, please just follow one of the options...

With all my respect. :pray:

**Pull request merged**
